# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v3.2.0
        hooks:
        -   id: trailing-whitespace
        -   id: end-of-file-fixer
        -   id: check-yaml
        -   id: check-added-large-files
    -   repo: https://github.com/pre-commit/mirrors-eslint
        rev: 'v8.52.0'
        hooks:
        -   id: eslint
            files: \.[jt]sx?$  # *.js, *.jsx, *.ts and *.tsx
            types: [file]
            additional_dependencies:
                - "eslint@^8.50.0"
                - "eslint-config-oclif@^5.0.0"
                - "eslint-config-oclif-typescript@^2.0.0"
                - "eslint-config-prettier@^9.0.0"
                - "eslint-plugin-unicorn@^48.0.0"
                - "eslint-plugin-node@^11.1.0"
                - "@typescript-eslint/eslint-plugin@^6.0.0"
                - "@typescript-eslint/parser@^6.0.0"
                - eslint-plugin-import@latest
                - eslint-plugin-mocha@latest
                - typescript@5
